package dev.twiceb.passwordsservice.service.util;

import org.springframework.stereotype.Component;

import javax.crypto.*;
import javax.crypto.spec.IvParameterSpec;
import java.nio.charset.StandardCharsets;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;

@Component
public class EnvelopeEncryption {

    // Method to generate a SecretKey for AES encryption
    public SecretKey generateKey() throws NoSuchAlgorithmException {
        KeyGenerator keygenerator = KeyGenerator.getInstance("AES");
        keygenerator.init(256); // Using AES with a key size of 256 bits
        return keygenerator.generateKey(); // Generating the SecretKey
    }

    // Method to generate an Initialization Vector (IV) for AES encryption
    public IvParameterSpec generateIv() {
        byte[] initializationVector = new byte[16]; // IV size for AES is 16 bytes (128 bits)
        SecureRandom secureRandom = new SecureRandom();
        secureRandom.nextBytes(initializationVector); // Generating random bytes for IV
        return new IvParameterSpec(initializationVector); // Creating IV using generated bytes
    }

    // Method to regenerate an IV from bytes
    public IvParameterSpec regenerateIvFromBytes(byte[] bytes) {
        return new IvParameterSpec(bytes); // Creating an IV from byte array
    }

    // Method to encrypt input using AES encryption with a given key and IV
    public byte[] encrypt(String input, SecretKey key, IvParameterSpec iv) throws Exception {
        Cipher cipher = Cipher.getInstance("AES/CFB8/NoPadding");
        cipher.init(Cipher.ENCRYPT_MODE, key, iv); // Initializing Cipher for encryption
        return cipher.doFinal(input.getBytes(StandardCharsets.UTF_8)); // Encrypting input text
    }

    // Method to decrypt cipher text using AES decryption with a given key and IV
    public String decrypt(byte[] cipherText, SecretKey key, IvParameterSpec iv) throws Exception {
        Cipher cipher = Cipher.getInstance("AES/CFB8/NoPadding");
        cipher.init(Cipher.DECRYPT_MODE, key, iv); // Initializing Cipher for decryption
        byte[] plainText = cipher.doFinal(cipherText); // Decrypting cipher text
        return new String(plainText); // Converting decrypted bytes to a string
    }
}
