FROM openjdk:22
LABEL authors="sebastian"

COPY target/eureka-server-0.0.1-SNAPSHOT.jar ./
CMD ["java", "-jar", "eureka-server-0.0.1-SNAPSHOT.jar"]
#FROM eclipse-temurin:21-jdk-alpine
#
#WORKDIR /app
#
#COPY ./target/eureka-server-0.0.1-SNAPSHOT.jar ./
#
#CMD ["java", "-jar", "eureka-server-0.0.1-SNAPSHOT.jar"]