#!/usr/bin/env bash

# Source the .env file
handleEnvFile() {
  if [ -f .env ]; then
      source .env
      echo "Environment variables loaded from .env file."

      # Check and set defaults if variables are empty or missing
      if [ -z "$PGADMIN_EMAIL" ]; then
        echo "Generated a default email for PGAdmin."
        PGADMIN_EMAIL="random@gmail.com"
        sed -i -E "s/^PGADMIN_EMAIL=.*/PGADMIN_EMAIL=$PGADMIN_EMAIL/" .env
      fi

      if [ -z "$RABBITMQ_USERNAME" ]; then
        echo "Generated a default username for Postgresl"
        RABBITMQ_USERNAME="default_rabbitmq_user"
        sed -i -E "s/^RABBITMQ_USERNAME=.*/RABBITMQ_USERNAME=$RABBITMQ_USERNAME/" .env
      fi

      if [ -z "$POSTGRES_USERNAME" ]; then
        echo "Generated a default username for Postgresl"
        POSTGRES_USERNAME="default_postgres_user"
        sed -i -E "s/^POSTGRES_USERNAME=.*/POSTGRES_USERNAME=$POSTGRES_USERNAME/" .env
      fi

      # Example: If the password is empty, generate an autogenerated password
      if [ -z "$PGADMIN_PASSWORD" ]; then
          PGADMIN_PASSWORD=$(openssl rand -base64 20 | tr -d '+/=')
          echo "Generated a new password for PGAdmin."
          # Update .env file with the generated password
          sed -i -E "s/^PGADMIN_PASSWORD=.*/PGADMIN_PASSWORD=$PGADMIN_PASSWORD/" .env
      fi

      # Example: If the username is empty, set a default username and update .env
      if [ -z "$RABBITMQ_PASSWORD" ]; then
          RABBITMQ_PASSWORD=$(openssl rand -base64 20 | tr -d '+/=')
          echo "Generated a new password for rabbitmq management."
          # Update .env file with the default username
          sed -i -E "s/^RABBITMQ_PASSWORD=.*/RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD/" .env
      fi

      if [ -z "$POSTGRES_PASSWORD" ]; then
        echo "Generated a new password for postgres."
        POSTGRES_PASSWORD=$(openssl rand -base64 20 | tr -d '+/=')
        sed -i -E "s/^POSTGRES_PASSWORD=.*/POSTGRES_PASSWORD=$POSTGRES_PASSWORD/" .env
      fi
      return 1
  else
      echo ".env file not found."
      return 0
  fi
}