package dev.twiceb.common.util;

import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;

import dev.twiceb.common.exception.ApiRequestException;

import javax.crypto.*;
import javax.crypto.spec.IvParameterSpec;

import static dev.twiceb.common.constants.ErrorMessage.INTERNAL_SERVER_ERROR;

import java.nio.charset.StandardCharsets;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
// this is a symmetric encryption.
// https://dev.java/learn/security/intro/ maybe from here?
// https://mkyong.com/java/java-aes-encryption-and-decryption/

@Component
public class EnvelopeEncryption {

    private static final int STANDARD_SECURITY_KEY_SIZE = 128; // bits
    private static final int MEDIUM_SECURITY_KEY_SIZE = 192; // bits
    private static final int HIGH_SECURITY_KEY_SIZE = 256; // bits
    private static final String DEFAULT_ALGORITHM = "AES";

    public int getHighSecurityKeySize() {
        return HIGH_SECURITY_KEY_SIZE;
    }

    // Method to generate a SecretKey for AES encryption
    public SecretKey generateKey() {
        try {
            KeyGenerator keygenerator = KeyGenerator.getInstance(DEFAULT_ALGORITHM);
            keygenerator.init(HIGH_SECURITY_KEY_SIZE, SecureRandom.getInstanceStrong()); // Using AES with a key size of
                                                                                         // 256 bits
            return keygenerator.generateKey(); // Generating the SecretKey

        } catch (NoSuchAlgorithmException e) {
            throw new ApiRequestException(INTERNAL_SERVER_ERROR, HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    // Method to generate an Initialization Vector (IV) for AES encryption
    public IvParameterSpec generateIv() {
        byte[] initializationVector = new byte[16]; // IV size for AES is 16 bytes (128 bits)
        SecureRandom secureRandom = new SecureRandom();
        secureRandom.nextBytes(initializationVector); // Generating random bytes for IV
        return new IvParameterSpec(initializationVector); // Creating IV using generated bytes
    }

    // Method to regenerate an IV from bytes
    public IvParameterSpec regenerateIvFromBytes(byte[] bytes) {
        return new IvParameterSpec(bytes); // Creating an IV from byte array
    }

    // Method to encrypt input using AES encryption with a given key and IV
    public byte[] encrypt(String input, SecretKey key, IvParameterSpec iv) {
        Cipher cipher = null;
        try {
            cipher = Cipher.getInstance("AES/CFB8/NoPadding");
            cipher.init(Cipher.ENCRYPT_MODE, key, iv); // Initializing Cipher for encryption
            return cipher.doFinal(input.getBytes(StandardCharsets.UTF_8)); // Encrypting input text
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // Method to decrypt cipher text using AES decryption with a given key and IV
    public String decrypt(byte[] cipherText, SecretKey key, IvParameterSpec iv) {
        Cipher cipher = null;
        try {
            cipher = Cipher.getInstance("AES/CFB8/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, key, iv); // Initializing Cipher for decryption
            byte[] plainText = cipher.doFinal(cipherText); // Decrypting cipher text
            return new String(plainText); // Converting decrypted bytes to a string
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
