import type { Metadata } from "next";

import "@/styles/globals.css";
import { AppProvider } from "./provider";
import { cn } from "@/helpers/common.helper";

export const metadata: Metadata = {
  title: "SyncTurtle | Simple life management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      {/* <link rel="preload" href={`http://localhost:8000/ui/v1/user/token `} as="fetch" crossOrigin="use-credentials" /> */}
      <body>
        <AppProvider>
          <div className={cn("h-screen w-full overflow-hidden relative flex flex-col")}>
            <div className="w-full h-full overflow-hidden relative">{children}</div>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
