import type { Metadata } from "next";

import "@/styles/globals.css";
import { AppProvider } from "./provider";
import { cn } from "@/helpers/common.helper";

export const metadata: Metadata = {
  title: "SyncTurtle | Simple life management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </head>
      <body>
        <AppProvider>
          <div className={cn("h-screen w-full overflow-hidden relative flex flex-col")}>
            <div className="w-full h-full overflow-hidden relative">{children}</div>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
