package dev.twiceb.common.enums;

public enum AuthErrorCodes {
    // Global
    INSTANCE_NOT_CONFIGURED(5000, "INSTANCE_NOT_CONFIGURED"), INVALID_EMAIL(5005, "INVALID_EMAIL"),
    EMAIL_REQUIRED(5010, "EMAIL_REQUIRED"), SIGNUP_DISABLED(5015, "SIGNUP_DISABLED"),
    MAGIC_LINK_LOGIN_DISABLED(5016, "MAGIC_LINK_LOGIN_DISABLED"),
    PASSWORD_LOGIN_DISABLED(5018, "PASSWORD_LOGIN_DISABLED"),
    USER_ACCOUNT_DEACTIVATED(5019, "USER_ACCOUNT_DEACTIVATED"),

    // Password strength
    INVALID_PASSWORD(5020, "INVALID_PASSWORD"), SMTP_NOT_CONFIGURED(5025, "SMTP_NOT_CONFIGURED"),

    // Sign Up
    USER_ALREADY_EXIST(5030, "USER_ALREADY_EXIST"),
    AUTHENTICATION_FAILED_SIGN_UP(5035, "AUTHENTICATION_FAILED_SIGN_UP"),
    REQUIRED_EMAIL_PASSWORD_SIGN_UP(5040, "REQUIRED_EMAIL_PASSWORD_SIGN_UP"),
    INVALID_EMAIL_SIGN_UP(5045, "INVALID_EMAIL_SIGN_UP"),
    INVALID_EMAIL_MAGIC_SIGN_UP(5050, "INVALID_EMAIL_MAGIC_SIGN_UP"),
    MAGIC_SIGN_UP_EMAIL_CODE_REQUIRED(5055, "MAGIC_SIGN_UP_EMAIL_CODE_REQUIRED"),
    EMAIL_PASSWORD_AUTHENTICATION_DISABLED(5056, "EMAIL_PASSWORD_AUTHENTICATION_DISABLED"),

    // Sign In
    USER_DOES_NOT_EXIST(5060, "USER_DOES_NOT_EXIST"),
    DEVICE_NOT_RECOGNIZE(5061, "DEVICE_NOT_RECOGNIZED"),
    EXPIRED_MAGIC_CODE_DEVICE(5062, "EXPIRED_MAGIC_CODE_DEVICE"),
    AUTHENTICATION_FAILED_SIGN_IN(5065, "AUTHENTICATION_FAILED_SIGN_IN"),
    REQUIRED_EMAIL_PASSWORD_SIGN_IN(5070, "REQUIRED_EMAIL_PASSWORD_SIGN_IN"),
    INVALID_EMAIL_SIGN_IN(5075, "INVALID_EMAIL_SIGN_IN"),
    INVALID_EMAIL_MAGIC_SIGN_IN(5080, "INVALID_EMAIL_MAGIC_SIGN_IN"),
    MAGIC_SIGN_IN_EMAIL_CODE_REQUIRED(5085, "MAGIC_SIGN_IN_EMAIL_CODE_REQUIRED"),

    // Both Sign in and Sign up for magic
    INVALID_MAGIC_CODE_SIGN_IN(5090, "INVALID_MAGIC_CODE_SIGN_IN"),
    INVALID_MAGIC_CODE_SIGN_UP(5092, "INVALID_MAGIC_CODE_SIGN_UP"),
    INVALID_MAGIC_CODE_DEVICE_VERIFICATION(5093, "INVALID_MAGIC_CODE_DEVICE_VERIFICATION"),
    EXPIRED_MAGIC_CODE_SIGN_IN(5095, "EXPIRED_MAGIC_CODE_SIGN_IN"),
    EXPIRED_MAGIC_CODE_SIGN_UP(5097, "EXPIRED_MAGIC_CODE_SIGN_UP"),
    EMAIL_CODE_ATTEMPT_EXHAUSTED_SIGN_IN(5100, "EMAIL_CODE_ATTEMPT_EXHAUSTED_SIGN_IN"),
    EMAIL_CODE_ATTEMPT_EXHAUSTED_SIGN_UP(5102, "EMAIL_CODE_ATTEMPT_EXHAUSTED_SIGN_UP"),
    DEVICE_CODE_ATTEMPT_EXHAUSTED_VERIFICATION(5103, "DEVICE_CODE_ATTEMPT_EXHAUSTED_VERIFICATION"),

    // OAuth
    OAUTH_NOT_CONFIGURED(5104, "OAUTH_NOT_CONFIGURED"),
    GOOGLE_NOT_CONFIGURED(5105, "GOOGLE_NOT_CONFIGURED"),
    GITHUB_NOT_CONFIGURED(5110, "GITHUB_NOT_CONFIGURED"),
    GITLAB_NOT_CONFIGURED(5111, "GITLAB_NOT_CONFIGURED"),
    GOOGLE_OAUTH_PROVIDER_ERROR(5115, "GOOGLE_OAUTH_PROVIDER_ERROR"),
    GITHUB_OAUTH_PROVIDER_ERROR(5120, "GITHUB_OAUTH_PROVIDER_ERROR"),
    GITLAB_OAUTH_PROVIDER_ERROR(5121, "GITLAB_OAUTH_PROVIDER_ERROR"),

    // Reset Password
    INVALID_PASSWORD_TOKEN(5125, "INVALID_PASSWORD_TOKEN"),
    EXPIRED_PASSWORD_TOKEN(5130, "EXPIRED_PASSWORD_TOKEN"),

    // Change Password
    INCORRECT_OLD_PASSWORD(5135, "INCORRECT_OLD_PASSWORD"),
    MISSING_PASSWORD(5138, "MISSING_PASSWORD"), INVALID_NEW_PASSWORD(5140, "INVALID_NEW_PASSWORD"),

    // Set password
    PASSWORD_ALREADY_SET(5145, "PASSWORD_ALREADY_SET"),

    // Admin
    ADMIN_ALREADY_EXIST(5150, "ADMIN_ALREADY_EXIST"),
    REQUIRED_ADMIN_EMAIL_PASSWORD_FIRST_NAME(5155, "REQUIRED_ADMIN_EMAIL_PASSWORD_FIRST_NAME"),
    INVALID_ADMIN_EMAIL(5160, "INVALID_ADMIN_EMAIL"),
    INVALID_ADMIN_PASSWORD(5165, "INVALID_ADMIN_PASSWORD"),
    REQUIRED_ADMIN_EMAIL_PASSWORD(5170, "REQUIRED_ADMIN_EMAIL_PASSWORD"),
    ADMIN_AUTHENTICATION_FAILED(5175, "ADMIN_AUTHENTICATION_FAILED"),
    ADMIN_USER_ALREADY_EXIST(5180, "ADMIN_USER_ALREADY_EXIST"),
    ADMIN_USER_DOES_NOT_EXIST(5185, "ADMIN_USER_DOES_NOT_EXIST"),
    ADMIN_USER_DEACTIVATED(5190, "ADMIN_USER_DEACTIVATED"),

    // Rate limit
    RATE_LIMIT_EXCEEDED(5900, "RATE_LIMIT_EXCEEDED"),

    // Unknown
    AUTHENTICATION_FAILED(5999, "AUTHENTICATION_FAILED");

    private final int code;
    private final String message;

    AuthErrorCodes(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public int getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }
}
