package dev.twiceb.common.enums;

public enum InstanceConfigurationKey {
    ENABLE_SIGNUP, ENABLE_MAGIC_LINK_LOGIN, ENABLE_EMAIL_PASSWORD, ENABLE_SMTP,
    DISABLE_WORKSPACE_CREATION, IS_GOOGLE_ENABLED, IS_GITHUB_ENABLED, IS_GITLAB_ENABLED,
    GITHUB_APP_NAME, EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD, EMAIL_PORT, EMAIL_FROM,
    EMAIL_USE_TLS, EMAIL_USE_SSL, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GITHUB_CLIENT_ID,
    GITHUB_CLIENT_SECRET, GITLAB_HOST, GITLAB_CLIENT_ID, GITLAB_CLIENT_SECRET
}
